---
apiVersion: "v1"
kind: "Namespace"
metadata:
  name: "default-1"
---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "crud"
  namespace: "default-1"
  labels:
    app: "crud"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: "crud"
  template:
    metadata:
      labels:
        app: "crud"
    spec:
      containers:
      - name: "crud-docker-1"
        image: "gcr.io/plenary-cat-362402/github.com/pedro-libera/crud-docker:$SHORT_SHA"
---
apiVersion: "autoscaling/v2beta1"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "crud-hpa-hswc"
  namespace: "default-1"
  labels:
    app: "crud"
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: "crud"
    apiVersion: "apps/v1"
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: "Resource"
    resource:
      name: "cpu"
      targetAverageUtilization: 80